### ISSUE TITLE
Don't make player plays his/her turn when he/she is already certain to win TB battle

### ISSUE THREAD

**Issue by souliane** [MrStahlfelge/lightblocks#18]
When playing a TB battle against somebody who dropped out, it is sometimes 100% sure that you will win even if you have played less turns than your opponent (because you already have more points at turn x than him/her as he/she died at turn x + 1).

In that case, I suggest to end the match and makes you win without having to play the turn x + 1. I don't see any reason to play that turn, but to see if the opponent sent you some lines, which has IMHO a very limited interest.

**Comment by MrStahlfelge** [comment]
You are right, it is boring to play the round.

There's even a more complex case: even if you need to play because the other player dropped out with slightly more points, the running turn could be immediately ended when you reached more points instantly.

I'll check what i can do and if I can change your case on server side only.

**Comment by MrStahlfelge** [comment]
Done with a server side change, change is in effect now. Please come back if you face any problems.
