### ISSUE TITLE
Add a "Challenge" button in the public profile

### ISSUE THREAD

**Issue by souliane** [MrStahlfelge/lightblocks#7]
It would be nice to be able to challenge someone when you are visiting his profile, e.g. with a button below the "Best scores" section.

**Comment by MrStahlfelge** [comment]
The reason I did not add it was because the profile can be opened from various game modes that are completely different from turn based battle mode. 
I think the button could be added for players that already know how the turn based battle works, and it should be labeled in a way that the user understands that you are challenging the other player in turn based battle. Do you have a suggestion for this label?

**Comment by souliane** [comment]
Mmm, what about "Challenge TB Battle"?

**Comment by MrStahlfelge** [comment]
Good idea.

The backend will send a flag at the profile to indicate if the button should be shown or not. For the first iteration, this will be true exactly if you (the requesting player) already played TB battle and the other player was active within the last three weeks (push notifications are only sent if the player was active within this period of time). At a later point of time, there can be more restrictions added in the backend (for example some players opting out, blocking others, ...)
